### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by svstoll** [svstoll/cscc-recommender#10]
- What types of evaluation make sense with the interaction data set?
- What is realistic to actually implement?

**Comment by Louis-Jin** [comment]
One thing I'm not sure is if we need to identify Overridden Methods. 
The method I knew needs to import the package for the API we want to check. In the original paper, they only used SWT and Swing/AWT, but our data is more general so I don't think we need to restrict the scope of API. And then it becomes hard to identify Overridden Methods.

**Comment by Louis-Jin** [comment]
in file CsccRecommender you mentioned
 // TODO: Identify identical completion events for evaluation --> same context, same selection, same type
I will assume you mean for Interaction dataset.
I don't think this is necessary, the algorithm is deterministic. Same class type and same context will give the same results. Plus, the chance for same context is very small, if this happens, probably means the user calls for recommender at the same place, and then, since we only use the results when the recommender gives the correct result, this is highly unlikely.

**Comment by svstoll** [comment]
I don't really understand the problem you described regarding overridden methods. Do you mean that we don't consider super classes of an invocation object when we query our index? If yes, then I don't know if it possible to resolve all super types of the invocation object with our dataset (I don't think so).

Regarding the duplicates: I found that there are many completion events for the same location, because users seem to trigger it multiple times. This would influence the evaluation as well, which is why I think we should filter them. But we could also check what other groups do in this regard.

**Comment by Louis-Jin** [comment]
I mentioned overridden methods only because in the evaluation part of the paper, they think it's harder to recommend overridden methods, so they also tried to see the results only for overridden methods. We can leave it since it's not very related to our dataset.

**Comment by Louis-Jin** [comment]
"Regarding the duplicates:"
Did you check if completionEvent.terminatedState == TerminationState.Applied, which should be 0. Because I can image they called recommender several times but only applied once. 
And if they called again and also applied, I think it should be considered correct two times... since the interaction matters more in this case, if this happens, it means this part is important. And we can see it as giving more weights to the ones that are more important.
